### ISSUE TITLE
config changes to discovery for es

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/elasticsearch-kubernetes#12]
according to https://www.elastic.co/guide/en/elasticsearch/guide/1.x/_important_configuration_changes.html#_minimum_master_nodes, 
config changes have been made to `discovery.zen` for several options. 
currently we set this in init/elasticsearch.yaml as : 
```
discovery:
  type: kubernetes
  zen:
    minimum_master_nodes: 2
```
but config changes require us to now use : 
```discovery.zen.hosts_provider: kubernetes
discovery.zen.minimum_master_nodes: 2
```
